/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.local.salarioliquido;

import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author vqb476
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSalarioBruto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumDependentes = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrevPrivada = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSalBruto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPercentualINSS = new javax.swing.JTextField();
        lblMsgParcelaINSS = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtValorINSS = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSalarioDescINSS = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDeducaoDependente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtDeducaoPrevPrivada = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtBaseIR = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtBaseIR1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtAliquotaIR = new javax.swing.JTextField();
        lblAliquotaIR = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtParcelaIR = new javax.swing.JTextField();
        lblMsgDeducaoIR = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtValorIR = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtSalarioINSS = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtValorIR1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtSalLiquido = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        txtPrevPrivada1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtNumDependentes1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtSalarioBruto1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));

        jLabel1.setText("Salário (R$):");

        txtSalarioBruto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSalarioBruto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel3.setText("Número de dependentes:");

        txtNumDependentes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel4.setText("Previdência Privada (%):");

        txtPrevPrivada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton1.setText("Calcular ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSalarioBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrevPrivada, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSalarioBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(txtNumDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(txtPrevPrivada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        jLabel2.setText("Salário Bruto:");

        txtSalBruto.setEditable(false);
        txtSalBruto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setText("X");

        jLabel6.setText("Percentual de desconto do INSS:");

        txtPercentualINSS.setEditable(false);
        txtPercentualINSS.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblMsgParcelaINSS.setText("---------------------------------------------");

        jLabel8.setText("=");

        jLabel9.setText("Valor do desconto do INSS:");

        txtValorINSS.setEditable(false);
        txtValorINSS.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel10.setText("Salário c/ desconto do INSS:");

        txtSalarioDescINSS.setEditable(false);
        txtSalarioDescINSS.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel11.setText("-");

        jLabel12.setText("Dedução por dependente:");

        txtDeducaoDependente.setEditable(false);
        txtDeducaoDependente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel13.setText("R$164,56 por dependente");

        jLabel14.setText("-");

        jLabel15.setText("Dedução da Previdência Privada:");

        txtDeducaoPrevPrivada.setEditable(false);
        txtDeducaoPrevPrivada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel16.setText("Valor base p/ cálculo do IR:");

        txtBaseIR.setEditable(false);
        txtBaseIR.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel17.setText("=");

        jLabel18.setText("Valor base p/ cálculo do IR:");

        txtBaseIR1.setEditable(false);
        txtBaseIR1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel19.setText("X");

        jLabel20.setText("Alíquota do IR (%):");

        txtAliquotaIR.setEditable(false);
        txtAliquotaIR.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblAliquotaIR.setText("----------------------------------------------");

        jLabel22.setText("-");

        jLabel23.setText("Parcela a deduzir do IR:");

        txtParcelaIR.setEditable(false);
        txtParcelaIR.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblMsgDeducaoIR.setText("----------------------------------------------------");

        jLabel25.setText("=");

        jLabel26.setText("Valor do desconto do IR:");

        txtValorIR.setEditable(false);
        txtValorIR.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel27.setText("Salário base p/ cálculo do IR:");

        txtSalarioINSS.setEditable(false);
        txtSalarioINSS.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel28.setText("-");

        jLabel29.setText("Valor do desconto do IR:");

        txtValorIR1.setEditable(false);
        txtValorIR1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel30.setText("=");

        jLabel31.setText("Salário Líquido:");

        txtSalLiquido.setEditable(false);
        txtSalLiquido.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtSalBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPercentualINSS, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMsgParcelaINSS))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txtSalarioDescINSS, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel11)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel20)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                        .addComponent(txtDeducaoDependente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel13)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel14))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                        .addComponent(txtAliquotaIR, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblAliquotaIR)))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel22))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtBaseIR1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel19)))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txtParcelaIR, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblMsgDeducaoIR)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel25))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(46, 46, 46)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtValorINSS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel15)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(txtDeducaoPrevPrivada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(32, 32, 32)
                                                        .addComponent(jLabel17)))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel16)
                                                    .addComponent(txtBaseIR, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtValorIR))
                        .addGap(160, 160, 160))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtSalarioINSS, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel28)
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtValorIR1))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSalLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSalBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtPercentualINSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMsgParcelaINSS)
                    .addComponent(jLabel8)
                    .addComponent(txtValorINSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSalarioDescINSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtDeducaoDependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(txtDeducaoPrevPrivada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBaseIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jLabel23)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBaseIR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtAliquotaIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAliquotaIR)
                    .addComponent(jLabel22)
                    .addComponent(txtParcelaIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMsgDeducaoIR)
                    .addComponent(jLabel25)
                    .addComponent(txtValorIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel29)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSalarioINSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(txtValorIR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(txtSalLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Fornecidos"));

        txtPrevPrivada1.setEditable(false);
        txtPrevPrivada1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel32.setText("Previdência Privada:");

        txtNumDependentes1.setEditable(false);
        txtNumDependentes1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel33.setText("Número de dependentes:");

        txtSalarioBruto1.setEditable(false);
        txtSalarioBruto1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel34.setText("Salário:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSalarioBruto1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumDependentes1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrevPrivada1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSalarioBruto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(txtNumDependentes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(txtPrevPrivada1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtSalarioBruto != null && !txtSalarioBruto.getText().trim().equals("") && !txtSalarioBruto.getText().equals("0")) {
            calculaSalarioLiquido();
        }
        else {
            JOptionPane.showMessageDialog(null, "Entre com um valor correto para o salário.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAliquotaIR;
    private javax.swing.JLabel lblMsgDeducaoIR;
    private javax.swing.JLabel lblMsgParcelaINSS;
    private javax.swing.JTextField txtAliquotaIR;
    private javax.swing.JTextField txtBaseIR;
    private javax.swing.JTextField txtBaseIR1;
    private javax.swing.JTextField txtDeducaoDependente;
    private javax.swing.JTextField txtDeducaoPrevPrivada;
    private javax.swing.JTextField txtNumDependentes;
    private javax.swing.JTextField txtNumDependentes1;
    private javax.swing.JTextField txtParcelaIR;
    private javax.swing.JTextField txtPercentualINSS;
    private javax.swing.JTextField txtPrevPrivada;
    private javax.swing.JTextField txtPrevPrivada1;
    private javax.swing.JTextField txtSalBruto;
    private javax.swing.JTextField txtSalLiquido;
    private javax.swing.JTextField txtSalarioBruto;
    private javax.swing.JTextField txtSalarioBruto1;
    private javax.swing.JTextField txtSalarioDescINSS;
    private javax.swing.JTextField txtSalarioINSS;
    private javax.swing.JTextField txtValorINSS;
    private javax.swing.JTextField txtValorIR;
    private javax.swing.JTextField txtValorIR1;
    // End of variables declaration//GEN-END:variables

    private void calculaSalarioLiquido() {
        //obtem os valores digitados
        double salarioBruto = Double.parseDouble(txtSalarioBruto.getText().replaceAll(",", "."));  
        double prevPrivada = Double.parseDouble(txtPrevPrivada.getText().replaceAll(",", "."));
        int numDependentes = Integer.parseInt(txtNumDependentes.getText());
        
        //preenche os dados fornecidos
        NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
        String porcentagem = String.valueOf(prevPrivada);
        txtSalarioBruto1.setText(nf.format(salarioBruto));
        txtNumDependentes1.setText(txtNumDependentes.getText());
        txtPrevPrivada1.setText(porcentagem.substring(porcentagem.length() - 1).equals("0") ? porcentagem.substring(0, porcentagem.length() - 2) + "%" : porcentagem.replaceAll("\\.", ",") + "%");
        
        //limpa os dados passados
        txtSalarioBruto.setText("");
        txtPrevPrivada.setText("");
        txtNumDependentes.setText("");
                
        //preenchendo e calculando resultados
        txtSalBruto.setText(nf.format(salarioBruto));
        
        //percentual de INSS
        double aliquotaINSS = calculaPercentualINSS(salarioBruto);
        String aliqINSS = String.valueOf(aliquotaINSS);
        txtPercentualINSS.setText(aliquotaINSS != -1 ? aliqINSS.substring(0, aliqINSS.length() - 2) + "%" : nf.format(430.78));
        String msgParcelaINSS = obtemMessagemParcelaINSS(aliquotaINSS);
        lblMsgParcelaINSS.setText(msgParcelaINSS);
  
        //calcula o valor do INSS
        double valorINSS = 0;
        if (aliquotaINSS == -1) {
            valorINSS = 430.78;
            txtValorINSS.setText(nf.format(valorINSS));
        }
        else {
            valorINSS = aliquotaINSS/100 * salarioBruto;
            txtValorINSS.setText(nf.format(valorINSS));
        }
        
        //calcula salario com desconto do INSS
        double salarioDescINSS = salarioBruto - valorINSS;
        txtSalarioDescINSS.setText(nf.format(salarioDescINSS));
        
        //calcula dedução por dependente
        double deducaoDependente = 0;
        if (numDependentes != 0 && numDependentes > 0) {
            deducaoDependente = numDependentes * 164.56;
            txtDeducaoDependente.setText(nf.format(deducaoDependente));
        }
        else {
            txtDeducaoDependente.setText(nf.format(0));            
        }
        
        //calcula deducao da previdencia privada
        double deducaoPrevPrivada = 0;
        if (prevPrivada != 0 && prevPrivada > 0) {
            deducaoPrevPrivada = salarioBruto * (prevPrivada/100);
            txtDeducaoPrevPrivada.setText(nf.format(deducaoPrevPrivada));
        }
        else {
            txtDeducaoPrevPrivada.setText(nf.format(0));            
        }
        
        //calcula o valor base para o IR
        double baseIR = salarioDescINSS - deducaoDependente - deducaoPrevPrivada;
        txtBaseIR.setText(nf.format(baseIR));
        txtBaseIR1.setText(nf.format(baseIR));
        
        //calcula aliquota do IR
        double aliquotaIR = obtemAliquotaIR(baseIR);
        String aliqIR = String.valueOf(aliquotaIR);
        if (aliquotaIR == 0) {
            txtAliquotaIR.setText("isento");
        }
        else {
            txtAliquotaIR.setText(aliqIR.substring(aliqIR.length()-1).equals("0") ? aliqIR.substring(0, aliqIR.length()-2) + "%" : aliqIR.replaceAll("\\.", ",") + "%");
        }
        
        //exibe mensagem da aliquota do IR
        lblAliquotaIR.setText(obtemMessagemAliquotaIR(aliquotaIR));
        
        //exibir a parcela a deduzir do IR
        double parcelaIR = obtemDeducaoIR(baseIR);
        if (aliquotaIR == 0) {
            txtParcelaIR.setText("isento");
        }
        else {
            txtParcelaIR.setText(nf.format(parcelaIR));
        }
        
        //exibe mensagem para a deducao da parcela do IR
        lblMsgDeducaoIR.setText(obtemMessagemAliquotaIR(aliquotaIR));
        
        //calcular o valor do IR
        double valorIR = (baseIR * (aliquotaIR/100)) - parcelaIR;
        txtValorIR.setText(nf.format(valorIR));
        txtValorIR1.setText(nf.format(valorIR));
        
        txtSalarioINSS.setText(nf.format(baseIR));
        
        //calcula salario liquido
        double salLiquido = baseIR - valorIR;
        txtSalLiquido.setText(nf.format(salLiquido));
    }

    private double calculaPercentualINSS(double salBruto) {
        int aliquota = 0;
        if (salBruto <= 1174.86) {
            aliquota = 8;
        }
        else if (salBruto >= 1174.87 && salBruto <= 1958.10) {
            aliquota = 9;
        }
        else if (salBruto >= 1958.11 && salBruto <= 3916.20){
            aliquota = 11;
        }
        else {
            aliquota = -1;
        }
        return aliquota;
    }

    private String obtemMessagemParcelaINSS(double aliquotaINSS) {
        String mensagem = "";
        if (aliquotaINSS == 8) {
            mensagem = "p/ salários até 1.174,86";
        }
        else if (aliquotaINSS == 9) {
            mensagem = "p/ salários de 1.174,87 a 1.958,10";
        }
        else if (aliquotaINSS == 11){
            mensagem = "p/ salários de 1.958,11 a 3.916,20";
        }
        else {
            mensagem = "p/ salários acima de 3.916,20";
        }
        return mensagem;
    }

    private double obtemAliquotaIR(double baseIR) {
        double aliquotaIR = 0;
        if (baseIR <= 1637.11) {
            aliquotaIR = 0;
        }
        else if (baseIR >= 1637.12 && baseIR <= 2453.50) {
            aliquotaIR = 7.5;
        }
        else if (baseIR >= 2453.51 && baseIR <= 3271.38) {
            aliquotaIR = 15;
        }
        else if (baseIR >= 3271.39 && baseIR <= 4087.65) {
            aliquotaIR = 22.5;
        }
        else {
            aliquotaIR = 27.5;
        }
        return aliquotaIR;
    }
    
    private String obtemMessagemAliquotaIR(double aliquotaIR) {
        String mensagem = "";
        if (aliquotaIR == 0) {
            mensagem = "p/ valor base até 1.637,11";
        }
        else if (aliquotaIR == 7.5) {
            mensagem = "p/ valor base de 1.637,12 a 2.453,50";
        }
        else if (aliquotaIR == 15){
            mensagem = "p/ valor base de 2.453,51 a 3.271,38";
        }
        else if (aliquotaIR == 22.5){
            mensagem = "p/ valor base de 3.271,39 a 4.087,65";
        }
        else {
            mensagem = "p/ valor base acima de 4.087,65";
        }
        return mensagem;
    }

    private double obtemDeducaoIR(double baseIR) {
        double deducaoIR = 0;
        if (baseIR <= 1637.11) {
            deducaoIR = 0;
        }
        else if (baseIR >= 1637.12 && baseIR <= 2453.50) {
            deducaoIR = 122.78;
        }
        else if (baseIR >= 2453.51 && baseIR <= 3271.38) {
            deducaoIR = 306.80;
        }
        else if (baseIR >= 3271.39 && baseIR <= 4087.65) {
            deducaoIR = 552.15;
        }
        else {
            deducaoIR = 756.53;
        }
        return deducaoIR;
    }
}
